### ISSUE TITLE
User modes aren't working

### ISSUE THREAD

**Issue by Tynach** [MCMrARM/revolution-irc#1]
I gave some feedback on the Play store about this, but I figured I'd put this here as well - and give some details about further attempts.

Originally, I noticed I could not set user modes for myself (such as `+p`) using the `/mode` command. However, I'm also noticing that I can't set them with `/raw` either.

Typing in `/raw MODE Tynach +p` causes a thing to pop up saying that no such command was found, but it lets me 'send as raw'... After which the server pops this message back at me:

> ```421 Tynach raw :Unknown command```

I finally got it to work by making my own custom command alias, but I feel like this sort of thing should be built in. I poked around the code a bit and saw [CommandAliasManager.java][1], and am tempted to simply send a pull request with an additional `mode` line... But I feel like it'd be more intuitive to users if the two could be merged somehow.

[1]: https://github.com/MCMrARM/revolution-irc/blob/master/app/src/main/java/io/mrarm/irc/config/CommandAliasManager.java

**Comment by MCMrARM** [comment]
My idea is to make it [channel-or-self] instead of [channel]. Most of the people aren't really IRC operators so making it [channel-or-user] is only going to be annoying likely.

**Comment by MCMrARM** [comment]
Also you found another issue, /raw is broken, I'll fix it in a bit.

**Comment by MCMrARM** [comment]
After thinking about it, it's not that simple. Indeed I'll want to define a second command alias I guess, or it'll get complicated otherwise.

**Comment by MCMrARM** [comment]
Well, for now to fix this I'll make the target parameter non-optional for /mode. I couldn't come up with anything better sadly.
https://github.com/MCMrARM/revolution-irc/commit/b758c8360f628e80a1286b68107cd83480e194ad
