### ISSUE TITLE
Overly optimistic notification state

### ISSUE THREAD

**Issue by Z1ni** [MCMrARM/revolution-irc#10]
Notification shows that the user is connected to a network while connecting or when connection attempt failed.
https://i.imgur.com/9DFQIDF.jpg

**Comment by MCMrARM** [comment]
Indeed it displays the count of active networks instead of actually connected. I guess this should be changed to a counter for connected, connecting and disconnected networks.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/revolution-irc/commit/1e4160c27856b0c2dff107ec1c7a40442caa207d
