### ISSUE TITLE
unresponsive blank tab after device unlocked

### ISSUE THREAD

**Issue by kurahaupo** [MCMrARM/revolution-irc#106]
When the device locks with revolutionIRC in the foreground, upon unlocking it shows a channel tab, but no text, and most UI elements are unresponsive.
However tapping ◀◼◼ returns to the connection list (via the device's home screen), and normal behaviour resumes.

**Comment by kurahaupo** [comment]
Any update on this? Can I give you logs or something?

I'm running Android 8.1

**Comment by MCMrARM** [comment]
I assigned it to 0.3.3 so I'll take a look later when I'll have some time to spend on this project.

**Comment by MCMrARM** [comment]
If you want to help to debug this, please join #revolutionirc on Freenode.

**Comment by kurahaupo** [comment]
[bugreport-marlin-OPM4.171019.021.P1-2018-08-09-11-57-15.zip](https://github.com/MCMrARM/revolution-irc/files/2280216/bugreport-marlin-OPM4.171019.021.P1-2018-08-09-11-57-15.zip)
![screenshot-2018-08-09-11-57-15-1](https://user-images.githubusercontent.com/197253/43991608-f152635e-9db3-11e8-9f7b-83c3afa46380.png)

**Comment by kurahaupo** [comment]
It _looks_ normal, but it's stuck, unresponsive.

**Comment by kurahaupo** [comment]
Ok, it's not entirely stuck.

The ⋯ menu operates, but shows "Settings" and "Exit" which conflicts with showing channels across the top of the screen.

The ≡ menu seems to operate, but selecting channels either (a) does nothing, or (b) shows the contents of the channel over-printed by the server-selection screen. (I'm not clear what selects between these two behaviours.)

If it gets into mode (b), then it's possible to do most in-channel functions normally, including swiping between channels, **except** that the server-chooser remains visible "over the top".

![image](https://user-images.githubusercontent.com/197253/43991849-74371b4e-9db8-11e8-8797-a96238b49d03.png)
![image](https://user-images.githubusercontent.com/197253/43991852-7943b660-9db8-11e8-975d-94d32c522ef0.png)
![image](https://user-images.githubusercontent.com/197253/43991856-7e4de068-9db8-11e8-8358-3da4099b5589.png)
![image](https://user-images.githubusercontent.com/197253/43991857-82cdae98-9db8-11e8-9b49-296a14d55386.png)

**Comment by kurahaupo** [comment]
(In case you're wondering, my time format is **%j-%H:%M:%S**)

**Comment by kurahaupo** [comment]
I'm now testing in Android 9.0, but that doesn't seem to have affected the behaviour significantly.

Note that to trigger this, you have to tap on the activity on the lock screen, rather than simply unlock

Here's a [sample sequence](https://photos.app.goo.gl/EtAeVtDVMiuQ9EDq6).

**Comment by kurahaupo** [comment]
Note how two screens seem to get overlaid:
![image](https://user-images.githubusercontent.com/197253/43992021-5fc7c8a4-9dbb-11e8-959f-bdc360203f6c.png)

**Comment by MCMrARM** [comment]
Thanks for the report! The notification thing is the thing triggering it and I successfully reproduced it in the current Google Play release (0.3.1).
However it doesn't happen in the current Git build, so I'm closing it :) (I believe it was fixed when fixing #33).
