### ISSUE TITLE
When kicked, show the kick message in the channel kicked from

### ISSUE THREAD

**Issue by ZeroKnight** [MCMrARM/revolution-irc#108]
As @kurahaupo mentioned in #100:
> When a user is kicked from a channel, it would be helpful to display that in the channel rather than in the server tab.

**Comment by kurahaupo** [comment]
Probably a duplicate of #65

**Comment by MCMrARM** [comment]
Not really, it's not a duplicate.

**Comment by MCMrARM** [comment]
Support for this has been merged: https://github.com/MCMrARM/revolution-irc/pull/136
