### ISSUE TITLE
Username autocompletion errors

### ISSUE THREAD

**Issue by Foxlider** [MCMrARM/revolution-irc#11]
Usually I use the auto-complete feature a lot but the keyboard auto-correct dont like it. It keeps the typed letters without keeping the whole username. 
For example if I type "Fox" and I press the auto-complete it will write "Foxlider" but as soon as I press the spacebar key it will keep "Fox".
I think it's possible to correct it since AndChat's auto-complete works

**Comment by MCMrARM** [comment]
What keyboard do you use? What Android version? Which autocomplete method do you use (double tap? the tab button? @ + nick?)?

**Comment by Foxlider** [comment]
I use the standard keyboard on my Samsung S7 on Nougat.
And I use the tab button


Le 16 oct. 2017 17:13, "MCMrARM" <notifications@github.com> a écrit :

What keyboard do you use? What Android version? Which autocomplete method
do you use (double tap? the tab button? @ + nick?)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MCMrARM/revolution-irc/issues/11#issuecomment-336918633>,
or mute the thread

**Comment by MCMrARM** [comment]
I can not reproduce. After autocompleting a space should be also automatically inserted, so the word should not disappear. Do you use the application-provided tab button enableable in settings or a keyboard provided tab button?

**Comment by Foxlider** [comment]
I am using the buit in tab button enabled in settings.

**Comment by Foxlider** [comment]
It seems to be an issue with global auto-complete. 
I typed '/n' ant tapped the '/nick <new pseudo>' option. It was written '/nick ' at first but when I started typing my pseudo, the n letter was still in front.

**Comment by MCMrARM** [comment]
I imagine this issue is related to the Samsung keyboard, I'll investigate it more over the next few days.

**Comment by MCMrARM** [comment]
Hopefully fixed with https://github.com/MCMrARM/revolution-irc/commit/bb0bfd2f39f0e96a96279a86ac586376f2a57213
If this issue will still happen with 0.3.1 which should be out in a few days, please reopen the issue.
