### ISSUE TITLE
Windows-1251 encoding support

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#117]
From a Google Play review.

**Comment by MCMrARM** [comment]
Implemented: https://github.com/MCMrARM/revolution-irc/commit/bab9d6dccff4e1c4d4c7fab01bb9ad0248de86cd

**Comment by smaragdus** [comment]
@MCMrARM 

I read here that [Windows-1251 encoding](https://en.wikipedia.org/wiki/Windows-1251) is supported, but I do not see it in the encoding list in server settings:

![](https://images2.imgbox.com/79/a6/egWmiwNV_o.png)

and I see unintelligible characters in channels list:

![](https://images2.imgbox.com/66/a8/1K7g2bdW_o.png)

and there are also unintelligible characters in users list:

![](https://images2.imgbox.com/89/3a/4lARS6DO_o.png)

As of version [0.5.5](https://github.com/MCMrARM/revolution-irc/releases/tag/0.5.5) I can barely use [Revolution IRC](https://github.com/MCMrARM/revolution-irc) with servers which use Windows-1251 encoding.

Am I missing something?

Regards
