### ISSUE TITLE
Can't find any way to read spoilered messages.

### ISSUE THREAD

**Issue by vaguerant** [MCMrARM/revolution-irc#118]
By spoilered messages, I mean messages where the user has set the same foreground and background colors on their text. Usually this would be a job for text selection, but I can select and copy and paste and resend a spoilered message without ever being able to see what it originally said.

**Comment by MCMrARM** [comment]
I guess this is impossible currently, if you have a newer device you can use Paste without formatting but on older ones you got to paste the text into a place that does not support formatting.

**Comment by MCMrARM** [comment]
You can now select parts of the message, and they'll be highlighted using the app's highlight color, essentially solving this.
