### ISSUE TITLE
Don't send notifications on NOTICEs

### ISSUE THREAD

**Issue by Mikaela** [MCMrARM/revolution-irc#12]
[The IRC RFC says:](https://tools.ietf.org/html/rfc1459#section-4.4.2)

```
4.4.2 Notice

      Command: NOTICE
   Parameters: <nickname> <text>

   The NOTICE message is used similarly to PRIVMSG.  The difference
   between NOTICE and PRIVMSG is that automatic replies must never be
   sent in response to a NOTICE message.  This rule applies to servers
   too - they must not send any error reply back to the client on
   receipt of a notice.  The object of this rule is to avoid loops
   between a client automatically sending something in response to
   something it received.  This is typically used by automatons (clients
   with either an AI or other interactive program controlling their
   actions) which are always seen to be replying lest they end up in a
   loop with another automaton.

   See PRIVMSG for more details on replies and examples.
```

and I see this generally interpreted that NOTICE is a less important message than PRIVMSG while Revolution IRC appears to send a notification and also vibrates and plays the notification sound.

In spirit of the RFC, my bot is sending all messages as notices except messages it relays from other networks and [Matrix](https://matrix.org) has copied this behaviour and their [IRC bridge](https://github.com/matrix-org/matrix-appservice-irc) causes all bot messages to appear as NOTICEs at IRC.

I think the easiest way to reproduce this on freenode is possibly to invite either `mijris[m]` or `ivar[m]` (Matrix bots) into any channel and saying `!ping` where they reply by saying `pong! <ISO8601 date>`. They accept all invites. (They also shouldn't rejoin after kicked.)

**Comment by michcioperz** [comment]
I think we could use a switch in the settings for that – if I remember, PIRC server ops like to notify about services downtime through NOTICE. (And anyway @MCMrARM loves to have lots of switches.)

**Comment by MCMrARM** [comment]
You are able to change this behavior for yourself in notification settings (Channel notices/Private notices). I'm unsure what the default setting should be, though, so this is about the default settings.

Sometimes I think some bots use NOTICEs to actually notify a user about something important. Also, as michcioperz has said some networks use NOTICEs to send important messages to all the network clients, so I'm unsure what should the default behaviour be.

**Comment by Mikaela** [comment]
Thanks, I had missed those settings.

I think the standard compliant default would be to not notify on NOTICEs (see the original submission) and it wouldn't annoy people who use NOTICEs as the RFC says as sometimes people using clients that beep on NOTICEs come to complain which I think is barking to the wrong tree.

**Comment by MCMrARM** [comment]
In 0.4.0, notices will no longer trigger notifications.

**Comment by MCMrARM** [comment]
Disabled channel notice notifications.

I'm unsure what the behavior for privmsg notices should be though?
