### ISSUE TITLE
Can't deal with irc: links 

### ISSUE THREAD

**Issue by jidanni** [MCMrARM/revolution-irc#125]
Can't deal with irc: protocol links like 
irc://irc.debian.org/#debconf-team properly.

**Comment by MCMrARM** [comment]
This is now fully implemented.

**Comment by yashpalgoyal1304** [comment]
hi, how can i test this?? i am running version 0.5.4 on android 7.0 . 
- I opened this issue in browser, and the irc link in description/first comment was not shown clickable to me.
- i tried selecting and sharing the link with RevIRC - didnt work. 
- i tried sharing to [OpenLinksWith](https://f-droid.org/packages/com.tasomaniac.openwith.floss), hoping that it will show RevIRC. But no go.
