### ISSUE TITLE
Default Port should already be filled in

### ISSUE THREAD

**Issue by jidanni** [MCMrARM/revolution-irc#126]
The default port number, 6667, should already be filled in for us.

**Comment by Mikaela** [comment]
I think the default port number should be 6697 and TLS enabled by default as Charybdis IRCd considers plaintext listeners as deprecated and cites RFCs 7194 & 7258.

* https://github.com/charybdis-ircd/charybdis/blob/charybdis-4.1/ircd/newconf.c#L888-L889
* [RFC 7194 - Default Port for Internet Relay Chat (IRC) via TLS/SSL](https://tools.ietf.org/html/rfc7194)
    * *This document describes the commonly accepted practice of listening
   on TCP port 6697 for incoming Internet Relay Chat (IRC) connections
   encrypted via TLS/SSL.*
* [ RFC 7258 - Pervasive Monitoring Is an Attack](https://tools.ietf.org/html/rfc7258)
    * *Pervasive monitoring is a technical attack that should be mitigated
   in the design of IETF protocols, where possible.*

**Comment by jidanni** [comment]
Ah, I only did a cursory web search and found 6667.
Anyway just like browsers don't ask the user to fill in port 80, etc.
users shouldn't be bothered to figure out the default.
Ah, no wonder circe-network-defaults does it as in
https://github.com/jorgenschaefer/circe/blob/master/circe.el .
Anyway by all means do it your way.
