### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by LuccoJ** [MCMrARM/revolution-irc#128]
Do you accept donations for this project anywhere?

If not yet, but might, personally I find it convenient to donate small sums for my Android apps on [Liberapay](https://liberapay.com/), given also that at least when SEPA transfers are available to someone, the fees are much less ridiculous than PayPal, or to just tap the Bitcoin donation icon in F-Droid when apps offer that (but that depends on how feasible small Bitcoin transactions are at a given time, which has a tendency to change in interesting ways).

In any case, I know F-Droid "supports" a certain number of donation platforms, in terms of placing neat-looking shortcuts to them in an app's description if the developers ask to have that included in the metadata.

**Comment by michcioperz** [comment]
MrARM has stated a few times already that at the time he has no intention of taking donations. Last time he stated so was just a few days ago in Revolution's IRC channel, so I suppose this stance is still up.

**Comment by LuccoJ** [comment]
Okay. I had considered asking on IRC, but no specific channel is stated in the readme here so I wouldn't have known where.

**Comment by michcioperz** [comment]
I suppose we need to add it to the README, it's #revolutionirc on Freenode (cc @MCMrARM)
