### ISSUE TITLE
App switcher window header doesn't match color scheme

### ISSUE THREAD

**Issue by MTres19** [MCMrARM/revolution-irc#13]
I chose a nice teal color in the settings:
![screenshot_2017-10-21-12-49-34](https://user-images.githubusercontent.com/18179456/31853877-57c10d5e-b65e-11e7-8d0b-ae732bb83269.png)

But the app switcher stays purple:
![screenshot_2017-10-21-12-50-29](https://user-images.githubusercontent.com/18179456/31853881-6f75fb26-b65e-11e7-9af4-8554ec572933.png)

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/revolution-irc/commit/f12306fdd47f15f0b268365e330908291d8cb33d
