### ISSUE TITLE
missing PONG

### ISSUE THREAD

**Issue by kurahaupo** [MCMrARM/revolution-irc#139]
At random intervals I receive "quit: kurahaupo has disconnected (Ping timeout: 260 seconds)" in each channel, followed by ":ERROR :Closing link {…my hostname…} (Ping timeout 260 seconds)" in the server tab. And then the TCP session is torn down, triggering auto-reconnection.

After discussion with freenode staff, it seems most likely that the client is failing to send PONG.

**Comment by kurahaupo** [comment]
Example transcript from a quiescent channel where I have been the only one present for the last 10 hours; see how I receive my own disconnection notices just before the connection drops each time:

08 01:19:36  * kurahaupo_ has joined
08 01:19:36  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions.
08 01:19:38  * ChanServ has left
08 01:21:00  * kurahaupo has disconnected (Read error: Connection reset by peer)
08 01:21:53  * kurahaupo has joined
08 01:21:53  * barjavel.freenode.net set channel modes 'sn'
08 01:22:39  * services. removed channel operator status from kurahaupo
08 01:22:39  * barjavel.freenode.net: *** Notice -- TS for #nerdnite changed from 1528384947 to 1428384526
08 01:22:39  * services. set channel modes 'ct', unset channel mode 's'
08 01:22:39  * ChanServ has joined
08 01:22:39  * services. gave channel operator status to ChanServ
08 01:22:39  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions., set by ChanServ
08 01:26:01  * kurahaupo has disconnected (Ping timeout: 240 seconds)
08 01:26:21  * kurahaupo has joined
08 01:26:21  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions.
08 06:28:13  * kurahaupo_ has joined
08 06:28:13  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions.
08 06:28:15  * ChanServ has left
08 06:29:52  * kurahaupo has disconnected (Ping timeout: 255 seconds)
08 06:35:04  * kurahaupo has joined
08 06:35:04  * verne.freenode.net set channel modes 'sn'
08 06:35:05  * services. removed channel operator status from kurahaupo
08 06:35:05  * verne.freenode.net: *** Notice -- TS for #nerdnite changed from 1528403741 to 1428384526
08 06:35:05  * services. set channel modes 'ct', unset channel mode 's'
08 06:35:05  * ChanServ has joined
08 06:35:05  * services. gave channel operator status to ChanServ
08 06:35:05  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions., set by ChanServ
08 09:18:26  * kurahaupo has disconnected (Ping timeout: 260 seconds)
08 09:18:51  * kurahaupo has joined
08 09:18:51  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions.
08 10:49:42  * kurahaupo_ has joined
08 10:49:42  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions.
08 10:49:43  * ChanServ has left
08 10:52:05  * kurahaupo has joined
08 10:52:05  * orwell.freenode.net set channel modes 'sn'
08 10:52:07  * services. removed channel operator status from kurahaupo
08 10:52:08  * orwell.freenode.net: *** Notice -- TS for #nerdnite changed from 1528419159 to 1428384526
08 10:52:08  * services. set channel modes 'ct', unset channel mode 's'
08 10:52:08  * ChanServ has joined
08 10:52:08  * services. gave channel operator status to ChanServ
08 10:52:08  * Topic: A mathematician, an engineer, and a scientist walk into a bar … coming soon near you, a meeting of contrary-minded nerds to listen to talks on interesting stuff and ask the speakers interesting questions., set by ChanServ

**Comment by kurahaupo** [comment]
I note that [client-PONG](https://tools.ietf.org/html/rfc1459#section-4.6.2) is implemented within [chatlib](/MCMrARM/chatlib/blob/master/chatlib/src/main/java/io/mrarm/chatlib/irc/handlers/PingCommandHandler.java), so it seems more likely that this is something to do with the device putting its WiFi transmitter to sleep, only to be woken up when the UI wakes up.

**Comment by the1glorfindel** [comment]
I am not getting the same messages as you are, but I also will have my "connection reset by peer" often if the app is not in the foreground, leading to joining and quiting in a long cycle. This is mostly annoying due to the notifications I get from the server when I join.
To reproduce all you should have to do is connect and then go to your home screen. I'm assuming this is mostly a fault of android trying to suspend background apps?

**Comment by kurahaupo** [comment]
Is there some logging I can turn on so that when it happens again, I can see what's happened?

**Comment by MCMrARM** [comment]
Please make sure the client-side PING is enabled in the Reconnection settings in the app.

If this still doesn't fix it then welp - perhaps 15 minutes is too low for a minimum value. But then comes the problem that going below will significantly increase battery drain - in the end, it really might be worth setting up a bouncer in the middle to make sure the app can safely reconnect as much as it needs.

**Comment by MCMrARM** [comment]
As for logging, the app logs all the messages into logcat.

**Comment by kurahaupo** [comment]
15 minutes is *way* too high.
That's less often than the UMTS keepalive or the server keepalive.
The server-side timeout on Freenode is around 4 minutes.

**Comment by the1glorfindel** [comment]
I have found that setting power management to manual has stopped my client from disconnecting while it's in the background. I believe that was a separate issue I had in that case though, as I never had it disconnect while in the foreground. @kurahaupo could you test and confirm either way?
On android 8 I went to settings -> battery -> apps -> set to manual management

**Comment by kurahaupo** [comment]
This is an issue that comes and goes, so it's hard to tell whether it's affected by (a) the version of RevolutionIRC, (b) the version of Android, (c) some peculiarity of my device, (d) misbehavior of my WiFi, (e) misbehavior of my UMTS data link, or (f) some interactions between all 5 of these factors.

I haven't seen the problem in a while, but that doesn't mean it won't crop up again; it has come and gone repeatedly over the last two years.

Google is between a rock and a hard place when it comes to Android; push one way and apps like RevolutionIRC break, push the other way and battery life sucks for everyone.

Right now they seem to have hit the sweet spot at least for me - battery good and always-connected apps like RevolutionIRC are behaving normally. But maybe it there someone with slightly different hardware is getting sucky battery life, and the next Android update intended to fix their problem will break RevolutionIRC again.

**Comment by kurahaupo** [comment]
(Just to be clear, yes I already had it in manual battery management mode.)

I haven't seen the connection drop while in the foreground since I last commented on this issue, but I do occasionally see that it has dropped while in the background. However that could be due to loss of whichever radio connection it's using rather than lack of CPU wakefulness.

Writing more details into the logs (especially including reasons for disconnections) would help if this ever comes up again. If it's _already_ written to logs, some way to get at the logs without having a rooted or unlocked phone would be handy.

**Comment by kurahaupo** [comment]
I haven't seen a repeat of this for several releases so I'm closing this issue.
If it recurs I'll open a new ticket and link to this one.
