### ISSUE TITLE
Publish 0.3.3 to GooglePlay

### ISSUE THREAD

**Issue by kurahaupo** [MCMrARM/revolution-irc#140]

**Comment by craftyguy** [comment]
@MCMrARM 

Making a new release would be great, since it seems like there are fixes in master for a number of annoying issues (e.g. notifications)..

**Comment by MCMrARM** [comment]
It's not ready yet, I'll finish it up when I'll be able to allocate some more time to this project.

**Comment by michcioperz** [comment]
Probably a good moment to close this.
