### ISSUE TITLE
Interface message formats control the wrong type of message 

### ISSUE THREAD

**Issue by camicarballo** [MCMrARM/revolution-irc#144]
Device: Samsung Galaxy S8
Model number: SM-G950U
OS: Android 8.0.0

Settings >> Interface >> Message Format >> (see below)

-- Message format
This seems like it should control the appearance of any message sent by any nick on any channel. However, this solely controls the appearance of messages sent by the user's nick on any given channel.

-- Message with mention format
This should control the appearance of messages sent by other nicks that mention your nick in the message text. However, this controls all messages sent by nicks other than the user's, regardless of the existence of any mention in the message.

**Comment by MCMrARM** [comment]
Looks like you added a match-all rule. This is the expected behavior currently, and there's an issue for it: https://github.com/MCMrARM/revolution-irc/issues/69
