### ISSUE TITLE
Offline messages not shown when reconnected after losing connection (using ZNC)

### ISSUE THREAD

**Issue by quaeched** [MCMrARM/revolution-irc#152]
I am connected to ZNC. When I click on "Disconnect and close" then reactivate the connection, it shows messages sent to me while I was offline. When I suddenly lose connection (e.g. WiFi turns off) and then it automatically reconnects, offline messages are not shown. Thanks.

**Comment by c776617** [comment]
Can confirm unfortunately, both with turning off wifi and turning off phone (shutdown feature). using lunarbnc on irc.freenode.net #test

**Comment by michcioperz** [comment]
I think this is probably a problem with the bouncers. If the connection is cut abruptly, the bouncer keeps sending the messages to the phone without storing them, until it realizes the connection was lost.

**Comment by c776617** [comment]
Mentioning this issue on znc's channel lead to this diagnosis:

that's likely not an abrupt disconnection, but instead causes a ping timeout, so ZNC doesn't actually know when you disconnected.

The [[playback]] or [[clearbufferonmsg]] modules were recommended.

https://wiki.znc.in/playback https://wiki.znc.in/clearbufferonmsg

**Comment by michcioperz** [comment]
Yeah, clearbufferonmsg is useful. Or generally disabling automatic buffer clearing and clearing it manually with `/znc clearbuffer #channel` (which is equivalent to `/msg *status clearbuffer #channel`)

**Comment by the1glorfindel** [comment]
This should be closed, imo. it's common across all irc clients and znc servers. if you ping out you will not receive the messages that were sent prior to the server disconnecting you.

**Comment by MCMrARM** [comment]
Indeed, this is not within of this project's scope.

**Comment by glechapelain** [comment]
I think this can be fixed! The result of the `write` function can be used as a feedback if the message made it through the wires
