### ISSUE TITLE
Notifications crash the application on Android 4.4 or lower

### ISSUE THREAD

**Issue by danieru98** [MCMrARM/revolution-irc#156]
Revolution IRC 0.4.1 will crash if a NOTICE message is received, whether is sent by a bot when joining a channel that is configured to send a message on user join, or a notice send by a user, the application will crash.

Edit: Android version: 4.2.2

**Comment by danieru98** [comment]
As far as I can tell, this bug was introduced after 0.3.2, As I remember being able to receive notices on that version just fine.
On the bright side I can now connect to QuakeNet and send messages to channels with version 0.4.1, so if the crash on NOTICE bug is fixed then this application will be just about perfect.

**Comment by danieru98** [comment]
Tested this bug on a emulator with android 4.4.2 and it happened in there too. Might be worth mentioning that michcioperz uses a znc, but I connect directly.

**Comment by kurahaupo** [comment]
I'm connected directly, using RevolutionIRC 0.4.1 on Android 9.

**Comment by danieru98** [comment]
Here's the logcat segment of the application crashing on android 4.2.2 after receiving a private NOTICE: https://paste.ubuntu.com/p/z9cGnxfFvt/

**Comment by danieru98** [comment]
Just realize that if the issue is indeed in the notification code, then any notification would crash the application on Android 4.4 or lower. So I tested with sending normal private messages and with just mentioning the nickname, and the application does indeed crash on those cases too as long as a notification is created.

**Comment by danieru98** [comment]
The bug is on line 158 of ChannelNotificationManager.java: https://github.com/MCMrARM/revolution-irc/blob/a79edd036db33070c6190892ba65d9d4f7cc369f/app/src/main/java/io/mrarm/irc/ChannelNotificationManager.java#L158
The issue is it's using a vector icon directly, but this is not supported on android 4.4 and lower. As stated here: https://developer.android.com/studio/write/vector-asset-studio?hl=en-419 "Android 4.4 (API level 20) and lower doesn't support vector drawables."

**Comment by MCMrARM** [comment]
Hello,
The only way is to prerender the images for notifications, as the VectorDrawableCompat does not work for notifications.

Thanks!
