### ISSUE TITLE
Database leak

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#157]
On Android Oreo, I have received the following message in logcat:

    09-17 13:05:28.135 11514 11523 W SQLiteConnectionPool: A SQLiteConnection object for database '/storage/emulated/0/Android/data/io.mrarm.irc/files/chat-logs/foo-bar-id/messages-2018-09-17.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

**Comment by MCMrARM** [comment]
This should be fixed with https://github.com/MCMrARM/chatlib-android-storage/commit/5c03349345f62a58e39c6806b3b6b3bf0b9215c8
