### ISSUE TITLE
Save unsent composed text

### ISSUE THREAD

**Issue by kurahaupo** [MCMrARM/revolution-irc#165]
Problem: input text is lost if up or down swipe occurs before it's sent.

Possible solution: save unsubmitted text as the newest history, if the input buffer is not empty when up or down is swiped.

Ideally it would be tagged such that if it's submitted, it's only saved once.

If it's recalled and then edited to clear the text, erase it from the history.

Also, have an option to keep separate history for each tab, and keep a separate composition buffer, by auto-saving in a similar manner which switching tabs.

**Comment by MCMrARM** [comment]
Implemented by:
https://github.com/MCMrARM/revolution-irc/commit/c56ccd4e780622d6ff6a86911a07c8ec3cc6d89e
https://github.com/MCMrARM/revolution-irc/commit/602c8070bae8f2110fa44d6a8250337a5dfd4508

**Comment by kurahaupo** [comment]
Thankyou!
