### ISSUE TITLE
Implement authentication with CertFP

### ISSUE THREAD

**Issue by tya99** [MCMrARM/revolution-irc#168]
This is useful for  [authentication with ZNC](https://wiki.znc.in/Certauth). Authentication in this manner means users of ZNC can enable [Auth Only Via Module](https://github.com/znc/znc/commit/42939c998f7eb73629d4fd2f13c27d2a6fb09dc9) disabling password authentication for extra security. Also mentioned in [RFC7194](https://tools.ietf.org/html/rfc7194#section-2.2.20).

Some networks such as [OFTC](https://www.oftc.net/NickServ/CertFP/), [Freenode](https://freenode.net/kb/answer/certfp) and [Rizon](https://wiki.rizon.net/index.php?title=CertFP) also use this method to authenticate (there are many other networks that also use it).

**Comment by MCMrARM** [comment]
Initial implementation: https://github.com/MCMrARM/revolution-irc/commit/fe5b3c3e94c663f01de74f40c8f63b696f0a0b23

**Comment by MCMrARM** [comment]
Implemented certificate generation (https://github.com/MCMrARM/revolution-irc/commit/d10f683d50ce2872f269ca40ba6ee8cf5048850c), marking this issue as complete.

Note that there's no simple way to export a certificate generated using this way. (You could technically backup data and copy it from the JSONs though).
