### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by clkircos** [MCMrARM/revolution-irc#17]
I've been receiving multiple notifications for a single message on my Pixel 2 XL, eg:

https://imgur.com/lC8jmBT

**Comment by MCMrARM** [comment]
This is... pretty bad and I can not reproduce it. Is this a bouncer (if so, what software)? Do the messages show up properly when you open the chat (there is a single one only)? Does it always happen? Does this happen immediately or you get a few notifications within a few second timespan?

**Comment by clkircos** [comment]
No bouncer. Yep only one message when I open the chat. It seems to always happen and I think they all come through immediately but I'm not positive.

**Comment by MCMrARM** [comment]
If you would like to help me debug the issue, you could join #revolutionirc on Freenode and I'll ask you to get a LogCat of a custom build to help me figure out the issue. I imagine this is a new bug with Android O.

**Comment by kuba-orlik** [comment]
I'm ready to help debug this issue! It does affect me on my Android 7.1. I will get a LogCat of a custom build, if you'll send it my way :)

**Comment by 19lmyers** [comment]
I think I'm also experiencing this issue.

**Comment by MCMrARM** [comment]
I still can't reproduce, but the cause in the code has been and this will be fixed.

**Comment by MCMrARM** [comment]
This has been fixed for 0.4.0 (earlier known as 0.3.3)
