### ISSUE TITLE
Crashes after establishing connection.

### ISSUE THREAD

**Issue by sarbash** [MCMrARM/revolution-irc#173]
Steps to reproduce:

1. Set a server.
2. See msg about connecting to the server.
3. After connection is established the crash message appears.
4. Restart the app.
5. After connection establishing crash is repeating.

IRC-server: **irc.librairc.net**

Huawei Honor 4C
Android 4.4.2 KitKat

UPD: Tried with SSL enabled/disabled. No difference.
UPD2: Just reinstalled the app. No success, the error persist.

**Comment by sarbash** [comment]
Little addendum: after few restarts and crashes, I had a luck to see the server logs in the app, but after short time the application crashes again. Also, I can see notifications and the NickServ notification in particular but when I tap on any of them the app crashes after short time.
I switched off reconnection option and finally get it stable after disconnection. But after manual reconnection it crashes again. Without connectings it's stable, no crashes.

**Comment by psukys** [comment]
Can't reproduce with 0.4.1 (installed through F-Droid) on Android 5.1.
Used default values and only changed the name and server address

**Comment by MCMrARM** [comment]
Does this only happen on that particular server? Can you try a server like Freenode?

**Comment by danieru98** [comment]
> Android 4.4.2 KitKat
> After connection is established the crash message appears.

> Can't reproduce with 0.4.1 on Android 5.1.

This sounds like bug https://github.com/MCMrARM/revolution-irc/issues/156
Try disabling notifications completely to confirm it's the same bug.

**Comment by Umeaboy** [comment]
I can confirm this issue using Lineage 15.1 on a Sony Xperia XZ Premium Dual (G8142).

Kernel 4.4.155-carbon kernel

The temporary workaround is to disable all notifications for this app.
