### ISSUE TITLE
certificates

### ISSUE THREAD

**Issue by heavytull** [MCMrARM/revolution-irc#176]
how certificates should be saved?
I installed the certificate at the level of the OS, android, but revolutionirc does not show it up in the certificate list tab in the server settings tab. I didn't find any option in revolutionirc settings for that.

**Comment by michcioperz** [comment]
I haven't used this feature in a long time, but I think it might be that when you connect to a server that presents a certificate that is not trusted by the system-level CAs, you will be given an option to save that certificate as trusted, and then it will appear on that list.

**Comment by MCMrARM** [comment]
System wide certificates are automatically trusted. Additionally, you get a prompt asking you whether you want to accept the certificate.

If you mean SASL client certificates, they're not supported.
