### ISSUE TITLE
Problem showing the words.

### ISSUE THREAD

**Issue by OriginCode** [MCMrARM/revolution-irc#18]
The letters which are coloured won't be appeared.

**Comment by MCMrARM** [comment]
I can not reproduce and am unsure when exactly does the issue happen. With formatted messages that you receive or in the editor? If it's a message that you receive could you please write the raw message in this issue? Otherwise, how to reproduce it exactly?

**Comment by OriginCode** [comment]
OK, I will send them on weekends.

**Comment by OriginCode** [comment]
![issue](https://user-images.githubusercontent.com/17294071/32272648-f694112c-bf39-11e7-9cbb-bc5edbc06369.png)
:arrow_up: Look at the latest message.
Raw message(From my IRC Bot): :teleboto!~teleboto@172.96.113.15 PRIVMSG #linuxba :2[OriginCoder-初中生] issue 测试

**Comment by OriginCode** [comment]
![issue2](https://user-images.githubusercontent.com/17294071/32272900-1d231a6c-bf3b-11e7-8a50-1149e7624b1d.png)
:arrow_up: Another...
Raw: :OriginCode!~OriginCod@unaffiliated/origincode PRIVMSG #linuxba :05TEST
05 is a colour code from WeeChat.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/revolution-irc/commit/4efc5eb629963dbda0087ade6a460888c03b89e3
