### ISSUE TITLE
Selecting a custom theme crashes the app

### ISSUE THREAD

**Issue by cbrt64** [MCMrARM/revolution-irc#183]
While grokking the new 0.5.0 update, I selected "Settings / Interface / Create a new theme", which promptly crashed the app. Launching the app was unsuccessful as long as this new custom theme was selected; clearing app data is not an option, since "App info / Manage space" also failed with a crash.

Having root, I was able to clear this failure by removing the `<string name="theme">custom:[GUID]</string>` line from `/data/data/io.mrarm.irc/shared_prefs/io.mrarm.irc_preferences.xml`. The newly-created custom theme is fully editable, but actually selecting it will start the crashing over again. I tried all this from a clean install as well, to rule out broken settings.

My phone is an LG-D851 (G3 with 32GB) on Android 5.0.1. This is probably relevant, as one user on IRC had no such problem. I am willing to help with further debugging as needed.

Some thoughts:
* Perhaps don't auto-select the new theme on creation?
* If you push a new update to fix this, it may be a good idea to clear the current theme selection on first run, for those unrooted users who may be in this predicament, and don't want to lose their data by way of uninstalling. This shouldn't be too intrusive, as 0.5.0 forgot my selection of the dark theme anyway.

**Comment by MCMrARM** [comment]
Assigning to 0.6, but I plan to actually fix it for a minor update (0.5.1?)

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/revolution-irc/commit/421d891f4b770232dd7086fe6ee7c0bdaeee9d8f
