### ISSUE TITLE
Allow server password field with other authentication options (SASL, CertFP etc).

### ISSUE THREAD

**Issue by tya99** [MCMrARM/revolution-irc#187]
Let me first thank you for implementing #168 

One small problem though is that when using [certauth](https://wiki.znc.in/Certauth) you actually need to specify a password as well.

> From now on you can log in to ZNC with any password but it cannot be blank. E.g. you can just send an "user@identifier/network:" as the server password. 

> :irc.znc.in 464 user :Password required

> :irc.znc.in *** You need to send your password. Configure your client to send a server password.

> :irc.znc.in *** To connect now, you can use /quote PASS <username>:<password>, or /quote PASS <username>/<network>:<password> to connect to a specific network.

**Comment by MCMrARM** [comment]
Why D:

**Comment by tya99** [comment]
> Ugh, just try to add the pass to the auto run command list, still, I think ZNC's behaviour makes very little sense :/

That is a work around for now yes. Unless the specification forbids a server password in conjunction with CertFP though it should be still added as an option. I can understand SASL and CertFP not being used in conjunction but I think you should be able to use a server pass.

The reason that using `/quote PASS` is probably undesirable is because the password is being stored in a text plain field rather than treated as a password and with password related APIs.

Perhaps a checkbox:

[ ] Server Password
(and when you tick it a password field appears).

**Comment by MCMrARM** [comment]
Except the ZNC's usage of password isn't a password at all. A checkbox is not an option as it bloats the UI too much. I'm considering adding a password field when CertFP is used though, however ZNC's usage of the password is IMHO wrong, very wrong.

**Comment by tya99** [comment]
> however ZNC's usage of the password is IMHO wrong, very wrong.

Yes I am inclined to agree with you. Considering https://github.com/znc/znc/issues/1410

There is an option to disable password authentication https://github.com/znc/znc/commit/42939c998f7eb73629d4fd2f13c27d2a6fb09dc9 however doing so means you cannot use the web interface anymore without a certificate. My web interface is only exposed to localhost anyway (behind ssh tunnel that requires ssh keys) so I'm not too worried about that.

**Comment by tya99** [comment]
> Just try to add the pass to the auto run command list, still

I did try that with: `/PASS user@identifier/network:` but it seems to not execute I put the command in the server window and sent it as a raw command and it seemed to work. Can the auto run command option allow for it to be sent raw?

**Comment by glguy** [comment]
I use the password to qualify for a certain connection class and separately I use client-side certificates to with SASL EXTERNAL / CERTFP to identify to NickServ. My use case for this feature is not only to work around the ZNC bug.

**Comment by tya99** [comment]
My understanding is the "server password" isn't really a password.

It's rather a string that is sent to the server, that will then allow the server to decide if you should be able to do other commands.

**Comment by MCMrARM** [comment]
I'll always enable the server password field for 0.5.1, due today.

**Comment by MCMrARM** [comment]
Implemented with https://github.com/MCMrARM/revolution-irc/commit/fc231bcc4f83e96572856affd34ea1294b5a256a

**Comment by Robby-** [comment]
I just saw this change in the update's changelog, this is so nice, I am on a server that requires SASL *and* a server password in order to connect. I just had to come here and say thank you!
