### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by Damianuscz** [MCMrARM/revolution-irc#193]
I can not change theme to Dark. When i kill app an restart it work but after few hours white theme is Back. Same issue on galaxy s7 and Huawei MediaPad M5 8.4

**Comment by MCMrARM** [comment]
Is this still an issue on 0.5.1?

**Comment by Damianuscz** [comment]
No. For me is closed

**Comment by shnee** [comment]
This bug still persists for me on 0.5.1

**Comment by Damianuscz** [comment]
HW /SW?

**Comment by shnee** [comment]
Android 8.0.0 on a OnePlus 3

**Comment by duggalsu** [comment]
I cannot change the theme. When I click on dark theme, nothing happens, the theme doesn't change - v.0.5.2, Android 11
