### ISSUE TITLE
Channel member names invisible on Android Pie 9

### ISSUE THREAD

**Issue by sebastiannielsen** [MCMrARM/revolution-irc#199]
Channel member names in list are invisible (White color) on Pie 9. (Samsung S8 Pie update).
Might need some forced color.

**Comment by MCMrARM** [comment]
:man_facepalming: sorry for this

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/revolution-irc/commit/5e2bf0b1be9be38c2c194da89e5c82b985815bf9

Not sure when I'll release it, I'll try to get it done as soon as possible.

As a workaround, create a custom theme, select CHAT, scroll down, and change the color for Normal members.
