### ISSUE TITLE
Easier switching between servers

### ISSUE THREAD

**Issue by AshenColors** [MCMrARM/revolution-irc#2]
As far as I can tell, when connected to multiple servers, the only way to switch between them or check for activity on the other ones is to open up the side panel. A gesture to switch servers or a button to quickly do so would be really nice (maybe lock open the side panel somehow?). My ideal interface would be something like a 'bar' of selectable servers next to the current server name (maybe even with activity indicators) but that seems like it'd be a lot more complicated.

This is also by far the best IRC client I've used on Android so far. Thank you for all the hard work you've put into it!

**Comment by MCMrARM** [comment]
As for locked drawer: I'd like it to be locked on tablets (probably toggle-able) and am going to implement it when I find some time to do that (as well as some other tablet UI improvements). On phones however, I don't think there is enough space for this.

I couldn't come up with a good UX for switching servers and I don't exactly understand how would you like this 'server' bar to look like. If you mean something like the channels bar, then I don't think two slideable bars on a single activity are a good idea.
What I could think of is to add a drop down icon after the server name and allow you to switch the servers using it, however I'm not sure if that's much more helpful than using the drawer.

Another thing I thought of is to make the Quick jump/Search button more available in the UI, but sadly I couldn't figure out how to make it look good as it always looks out-of-context in the appbar.

**Comment by AshenColors** [comment]
My particular usecase is a Chromebook with Android app support (which, incidentally, Revolution supports nicely with changing resolutions on the fly). The locking drawer would be a lovely enhancement and would work nicely for what I had in mind.

I don't particularly have a better idea than a second sliding bar. My only other UX idea is to display all currently connected channels in the 'channel' sliding bar, regardless of server, but as a lowly end user I don't know if this is either technically feasible or a good idea.

Thanks again!

**Comment by MCMrARM** [comment]
I will implement drawer pinning for the next beta release. I will also try to implement a double-shift key press to show up the search menu.

As for a second sliding bar I don't like the idea. I might implement all-channels-in-a-single-tab-view in a later release.

**Comment by MCMrARM** [comment]
I have implemented the drawer pinning mostly (https://github.com/MCMrARM/revolution-irc/commit/f22642891f589a6a809516d06570422e14478221 https://github.com/MCMrARM/revolution-irc/commit/555db71c47e2691a2f80dad1a6904e7f54350243 https://github.com/MCMrARM/revolution-irc/commit/bf912b3ce3dda953e19943a34ae4308408312d29). I still need to tweak it a little bit but it's mostly done and definitely coming for the next beta release which I hope to get out in a few days (when it actually comes on depends mostly on how quickly will I be able to fix a few bugs I noticed).

**Comment by TheMythPT** [comment]
:+1:
