### ISSUE TITLE
Option to sort channels alphabetically automatically 

### ISSUE THREAD

**Issue by RX14** [MCMrARM/revolution-irc#20]
Title says it all, honestly. When znc autojoins me to all my channels it'd be great if the channels were inserted in sorted order.

**Comment by RX14** [comment]
Turns out this is simply capitalized channels sorting before uncapitalized ones.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/revolution-irc/commit/e4d2d641f58dc412bfbb2d00f5b637d00f8a8bae
