### ISSUE TITLE
Regular nicks unreadable in light theme

### ISSUE THREAD

**Issue by 14mRh4X0r** [MCMrARM/revolution-irc#200]
In the light theme, regular nicks in the nick list are white against a very light grey background, and thus unreadable.

Phone: Xiaomi Mi A2 Lite, Android 9 (Android One)

**Comment by MCMrARM** [comment]
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/199

**Comment by 14mRh4X0r** [comment]
Oops, sorry
