### ISSUE TITLE
Crash when editing colors manually.

### ISSUE THREAD

**Issue by kaeza** [MCMrARM/revolution-irc#201]
Steps to reproduce:

- Create a new theme.
- Tap on a color.
- Tap e.g. on the hex EditText.
- Delete chars until there's only a '#'.
- The app crashes.

Don't have a traceback at hand, sorry.

Edit: Using 0.5.1 from F-Droid.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/revolution-irc/commit/84927356f2244ac0a346c92988790507e21f34b6

**Comment by kaeza** [comment]
Thank you!
