### ISSUE TITLE
Old logs deleted.

### ISSUE THREAD

**Issue by kaeza** [MCMrARM/revolution-irc#203]
Since updating to 5.0.1, old logs are being deleted even though I have set storage to unlimited.

I didn't see any options besides the aforementioned storage settings. Is this a bug or am I missing something?

Edit: to clarify, only today's logs are seen, for any value of today. I.e. logs are only visible from 00:00 of the current day.

**Comment by MCMrARM** [comment]
Yes, it's known bug in 0.5.1, sorry.
Fixed by https://github.com/MCMrARM/revolution-irc/commit/bdabd4d1f29cfdab187bfccb4e0b087212d7e75e

**Comment by kaeza** [comment]
Thank you again :)
