### ISSUE TITLE
F-Droid version mismatch

### ISSUE THREAD

**Issue by Grossdm** [MCMrARM/revolution-irc#210]
Hello,

[Yalp](https://github.com/yeriomin/YalpStore) has been attempting to update Revolution IRC, but fails with a signature mismatch.

It seems that Revolution IRC is releasing new versions that are delayed in getting to F-Droid.

From what I've read, F-Droid requires some effort for developers to "get the hang of".

If it is possible to prevent delays in updating the F-Droid repo, I'm sure there are many users that would appreciate this very much.

Thank you!

**Comment by michcioperz** [comment]
The delays on F-Droid are caused by F-Droid. All apps released on F-Droid are delayed compared to their Github due to their build and release process, from what I know.

**Comment by MCMrARM** [comment]
Also might be related to the fact I recently mess up and end up deleting releases within 5 minutes (more exactly I did that twice).

But yeah, the delay can't be controlled by me I think?

**Comment by Poussinou** [comment]
Hi, F-Droid contributor here.

Please delete your 0.5.2 tag, and retag it with the last commit you did included. The VersionCode (that you changed in this last commit) needs to be updated between each release, otherwise we cannot build.

Thanks

**Comment by MCMrARM** [comment]
Oops, I messed up indeed. I don't know why the version code was not updated on Git, but thanks for pointing this out, I will correct this later today.

**Comment by leo-lb** [comment]
@MCMrARM Have you been through it? That log bug is very annoying and I can't update with another apk that's not from F-Droid without losing all data..

Your application is amazing, thanks for the great work, without that bug I practically did not need a bouncer to have all IRC logs with mobile data, it's not damaging battery life either.

**Comment by leo-lb** [comment]
@Poussinou It seems like the changes have been made but F-Droid still hasnt picked up the change. What is up?

**Comment by Poussinou** [comment]
@leo-lb Nothing changed, we need the last commit to be included IN the 0.5.2 tag, that's still not the case. Only @MCMrARM can do something about this, not the F-Droid fault

**Comment by leo-lb** [comment]
@Poussinou Ahh okay, well hope they do it soon! :)

**Comment by MCMrARM** [comment]
Yeah sorry, let me fix this now.

**Comment by MCMrARM** [comment]
Fixed hopefully

**Comment by leo-lb** [comment]
@MCMrARM Thanks!
@Poussinou Is it possible to trigger the update on F-Droid now? It's been a while already.
