### ISSUE TITLE
Possible to connect to first server automatically?

### ISSUE THREAD

**Issue by cellojaan** [MCMrARM/revolution-irc#213]
Hi.

Possible to connect added server automatically when app start? I want to use this library for only my server?

Thanks.

**Comment by MCMrARM** [comment]
Use the [Exit] functionality which saves the servers you have been connected to.

**Comment by cellojaan** [comment]
> Use the [Exit] functionality which saves the servers you have been connected to.

Hi @MCMrARM 

I really do not know how I can do it. Can you give a example please?

**Comment by michcioperz** [comment]
Connect to a server, then go to the servers list, and from the three dots menu choose Exit. When you open the app again, you will be reconnected to all servers you were connected to when you pressed Exit.

**Comment by TheMythPT** [comment]
![Screenshot_20190404-124705](https://user-images.githubusercontent.com/25697531/55550201-f6cb8080-56d7-11e9-8129-2214710b9d16.jpg)
![Screenshot_20190404-124730](https://user-images.githubusercontent.com/25697531/55550209-fd59f800-56d7-11e9-8a43-9690f95b6f16.jpg)
