### ISSUE TITLE
Make kebab menu (3 dot menu) simpler and have only 'close tab'

### ISSUE THREAD

**Issue by roboirc** [MCMrARM/revolution-irc#216]
Right now if we click on the menu while in a channel tab it shows "Leave channel" or in a conversation tab it shows "Close conversation". Instead of making it so complicated, just have the same option in all tabs as "Close tab". Thanks!

**Comment by MCMrARM** [comment]
I think this is actually wrong.

Leave channel sends a leave message to the server and changes the server state.
Close conversation merely hides the conversation from the locally tracked list.

**Comment by roboirc** [comment]
I know what "Leave channel" and "Close conversation" do but for the UI it would be nicer and simpler to show only "Close Tab" to the user but do whatever you want for that option in the background.

**Comment by MCMrARM** [comment]
This perhaps would make it less confusing for a newcomer, but imo this is a very bad idea and will confuse anyone who's not a newcomer to IRC. IMO "Close tab" is confusing and is not clear as to what it does - it could just close the tab, without leaving the channel. Leave conversation would be better but then do you actually leave the conversation? Not really, you just close it. Therefore the split does make sense and "Close tab", imho, is only an improvement for a newcomer.

**Comment by jzabroski** [comment]
I think the terminology should be "Hide tab" as opposed to "Close tab".  Close sounds destructive.

**Comment by MCMrARM** [comment]
:thinking: That... makes sense, I guess. I think "Close tab" is fine though, I mean, it's not "Delete conversation", but merely "Close tab", though I can see it could be confusing. Will give it a thought for newui.
