### ISSUE TITLE
Adding or editing a server crashes the app when primary colour is not default

### ISSUE THREAD

**Issue by Vexatos** [MCMrARM/revolution-irc#22]
When you change the primary or accent colour in the settings, adding or editing a server crashes the app; also occurs when trying to add new command aliases or custom notification rules. Also, there doesn't seem to be a way to change the colours back to "Default".

Using a Samsung Galaxy J3 (SM-J320F) on Android 5.1.1.

**Comment by Vexatos** [comment]
Turns out it only seems to occur when primary colour is changed.

**Comment by MCMrARM** [comment]
Note: This issue happens on 5.0 and 5.1 only.
