### ISSUE TITLE
Wrong color on ^C

### ISSUE THREAD

**Issue by svbeon** [MCMrARM/revolution-irc#23]
^C in dark theme revert the text colour to black instead of white (my set message colour) but only in notices

**Comment by svbeon** [comment]
As a sidenote, I must say that I think this app is awesome! It has all the features I've lacked and so deeply craved! THANKS!

**Comment by MCMrARM** [comment]
Is this still an issue in 0.3.2? Some changes were made to the color parsing code.

**Comment by svbeon** [comment]
Hmm I'll check. In `0.3.2` weechat receives the colours weirdly

**Comment by kurahaupo** [comment]
While on the subject of wrong colours, it appears that ^C**0** and ^C**1** are swapped.

According to https://www.mirc.com/colors.html they should be white & black respectively.

**Comment by benrob0329** [comment]
[This](http://modern.ircdocs.horse/formatting.html) is probably the best source for current formatting standards.

**Comment by currificado** [comment]
As @kurahaupo said, the mIRC colors 0 and 1 are swapped. Could it be fixed?
