### ISSUE TITLE
inputbox becomes weird after pasting text from clipboard

### ISSUE THREAD

**Issue by LaineZ** [MCMrARM/revolution-irc#236]
inputbox is going crazy after pasting text from clipboard (input-lag, autocomplete clears word completely and after undetermined time app crashes...
it is possible that this is not client bug
Android 7.0, Revolution IRC 0.5.2, Keyboard: Gboard 5.1.18

**Comment by MCMrARM** [comment]
Duplicate of https://github.com/MCMrARM/revolution-irc/issues/141
