### ISSUE TITLE
Cannot set server-specific commands as autorun

### ISSUE THREAD

**Issue by thomasrussellmurphy** [MCMrARM/revolution-irc#241]
A server I'm on has server-specific aliases `/nickserv` and `/chanserv` that work when "send as raw" is selected during interactive use, but trying to use them in the server autorun settings results in an error message. Is it reasonable to automatically allow these commands here?

Version: 0.5.0/Google Play

**Comment by PeGaSuS-Coder** [comment]
Did you tried to add them as `/raw command`?

It works for me with `/raw ns help`, as example.

Cheers

**Comment by thomasrussellmurphy** [comment]
That is indeed the way to force sending commands as raw. Thanks!
