### ISSUE TITLE
bug(?): The server address is not long enough

### ISSUE THREAD

**Issue by Kreyren** [MCMrARM/revolution-irc#243]
I want to wrap revolutionIRC in tor using orbot per application and then connect on freenode which has dedicated address as `ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion` which is too long for revolutionIRC to accept.

Requesting it to be extended.

### Steps to reproduce

1. Copy and paste `ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion`  from https://freenode.net/kb/answer/chat in revolution-irc
2. expect it to past only `ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd`

**Comment by MCMrARM** [comment]
I am not aware on any text length restriction on that field though...

**Comment by Kreyren** [comment]
@MCMrARM Added steps to reproduce

**Comment by Kreyren** [comment]
@MCMrARM update: it seems tha ti am able to add `.onion` to that url so this seems to be an issue with pasting text in that field?

**Comment by Kreyren** [comment]
@MCMrARM Sorry this is pebcak my phone did not select the whole thing and it was difficult to see on the GUI.
