### ISSUE TITLE
[Suggestion] [Request] Disable Skin Limitation On Minecraft Bedrock.

### ISSUE THREAD

**Issue by Yuuki-kito** [MCMrARM/revolution-irc#249]
Minecraft Bedrock actually works for OBJ Models, but since the new function on Minecraft 1.2, Minecraft Bedrock no longer supports for custom geometry and OBJ Files. A few people can still using custom geometry using injector. Also your OBJtoSkin (Skin Studio) is limited because of this function.

**Comment by NitroNils** [comment]
I think you are in the wrong repository, mate 😂
