### ISSUE TITLE
Maxlength messages

### ISSUE THREAD

**Issue by svbeon** [MCMrARM/revolution-irc#25]
It'd be nice if the app either automatically split messages longer than the maximum allowed length, or stopped you from typing longer than it. Right now it just cuts and the complete message doesn't come through

**Comment by Mikaela** [comment]
For me it doesn't even cut as seen in #102, it doesn't send the message at all.

**Comment by kurahaupo** [comment]
I suspect there's differing behaviours among servers when they receive an over-long line; truncate & discard are both possible actions.

There's a good explanation at https://developer.pidgin.im/ticket/7672

**Comment by Heufneutje** [comment]
My experience is that some servers will auto-split the message for you, but most of them will truncate it. Splitting client side seems to be the best solution.

**Comment by MCMrARM** [comment]
Implemented by https://github.com/MCMrARM/chatlib/commit/397599851ff28c39bf571652147cbd0daf87b5a2
