### ISSUE TITLE
ENHANCEMENT: Include own keyboard to bypass OS eavesdropping

### ISSUE THREAD

**Issue by jbrepogmailcom** [MCMrARM/revolution-irc#254]
Currently keystrokes go from keyboard to application through OS APIs, so OS can see whatever is typed. I would recommend to include some opensource keyboard (AnySoftKey, Hacker keyboard) directly in the application so keys cannot be intercepted by OS (Google). You would be _the only messaging application_ with this high level of security.

**Comment by MCMrARM** [comment]
I mean the framework is OS provided so they just could upload all textboxes in every app to a server if Google is your threat actor. Distrusting the OS services sounds meaningless if the framework is OS provided as well and all text can be fetched via accessibility APIs.

**Comment by MCMrARM** [comment]
I am closing this issue as out of scope.
