### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by LatinCoder18** [MCMrARM/revolution-irc#257]
I have a problem - I am trying to rename the packages of my Android application with Android Studio, but it turns out that following the steps of other guides after giving refactor does not give me the option to rename the package.

Instead it gives me to rename the directory directly and I don't know what to do with that.

https://i.stack.imgur.com/nIuSj.png

**Comment by MCMrARM** [comment]
I don't know why you would want to do that though.

**Comment by kurahaupo** [comment]
In Java and related languages, package names are directly tied to source directory names, so changing the latter is _how_ you change the former.
