### ISSUE TITLE
Messages ending up in the wrong window

### ISSUE THREAD

**Issue by svbeon** [MCMrARM/revolution-irc#26]
So, I had twl query windows open, I `/msg dax Some message`, when he replied it ended up in the query window I had with myself (for testing purposes, duh) see below

![screenshot_20171104-210321_01_01](https://user-images.githubusercontent.com/10356719/32409040-1a3d5d38-c1a4-11e7-9227-e6345fcd6cf4.jpg)

**Comment by svbeon** [comment]
As it turns out, having a query windows open with yourself results in all private messages ending up in there, and no new windows beeing opened when someone /msg you

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/chatlib/commit/25cd4ec22cf7d19abdef8076627ac67e36e834a2, which I want to get out soon.

**Comment by svbeon** [comment]
Splendid! Once again, a big thanks for this wonderful app!

**Comment by MCMrARM** [comment]
Yes, after I fix how I manage chatlib and chatlib-android as dependencies.
