### ISSUE TITLE
Update app

### ISSUE THREAD

**Issue by duggalsu** [MCMrARM/revolution-irc#266]
I would like to update the app for SdkVersion 11 and also update any libs / tools versions for security.
- Shall I open a PR ?
- Shall I also bump the version code and version name to 0.5.3 so that it gets pushed to fdroid ?

**Comment by MCMrARM** [comment]
Sure. Version code bump is also okay.

Thanks!

**Comment by duggalsu** [comment]
Do we need to do anything to publish the new version on fdroid?

**Comment by duggalsu** [comment]
Is there anything stopping the new release?

**Comment by MCMrARM** [comment]
I forgot you have to create a Github release, sorry! I created one hopefully this will be enough.
