### ISSUE TITLE
Nick's status isn't shown

### ISSUE THREAD

**Issue by svbeon** [MCMrARM/revolution-irc#27]
So, it'd be great if we could have `@` for operators and `+` for voiced users, currently it only shows
`[HH:mm] <Nick> message` whereas I'd love if it showed `[HH:mm] <@Nick> message` for channel operators. Like it's visible in the channels nicklist

**Comment by MCMrARM** [comment]
Feature implementation: https://github.com/MCMrARM/revolution-irc/commit/ca3f6f216c0092eed8b095a2e73ea96f8394ddcb
I still need to add the new chip to the default presets so not closing the issue just yet.

**Comment by svbeon** [comment]
\o/ if you want to dig further into this there's, of course, look into the [multi prefix spec](http://ircv3.net/specs/extensions/multi-prefix-3.1.html) and [account-tag](http://ircv3.net/specs/extensions/account-tag-3.2.html) or it's predecessor [identify-msg](https://github.com/grawity/irc-docs/blob/master/client/cap-identify-msg.md) that could give a neat prompt if a user is signed in or not. that might however be a very niche group of us that use that, so I wouldn't put it as top priority, if it were to ever be implemented

**Comment by MCMrARM** [comment]
The application supports the multi-prefix spec, but it does not display the extra prefixes anywhere currently. They're used for internal state tracking only and I don't think displaying them would do any good.
I don't know of a IRCd or bouncer supporting the `identify-msg` spec.

**Comment by svbeon** [comment]
Yeah, as mentioned it might just be for a niche group of users (notably operators like me) perhaps multi prefix could be shown in the whois window.

I know [ircd-seven](https://github.com/freenode/ircd-seven/blob/master/extensions/identify_msg.c) supports identify-msg, but upon further investigation I realize that might be the only one currently. Once again, it's a niche potential userbase, so I wouldn't make it a giant priority, but if you feel that you have a moment or two over later on in the development, I would be very very happy to have the options :)

**Comment by Mikaela** [comment]
`identify-msg` is the only IRCd that has ircd-seven and I think the general consensus is that it shouldn't be supported, see https://github.com/ircv3/ircv3-specifications/issues/198#issuecomment-166980830 .

> Identify-msg is almost useless, because it doesn't tell you what account they're identified to. Also, freenode's identify-msg will report - if you're not using a nick grouped to the account you're identified to. This is better solved with account-tag.

> The combination of account-notify, account-tag and extended-join make identify-msg not needed.

**Comment by svbeon** [comment]
@Mikaela yes, hence my "or" in above reply, I had the ircv3 specs as the one I recommended rather than `identify-msg`

**Comment by MCMrARM** [comment]
I missed over the part mentioning `account-tag`, but I don't know of a IRCd supporting `account-tag` either?

**Comment by svbeon** [comment]
there's a [handy table](http://ircv3.net/software/servers.html) for that.

but at a glance, 2017-11-23 it's those:
![suport-table-screenshot](https://i.imgur.com/JB68Bvr.png)

**Comment by MCMrARM** [comment]
This closes this issue: https://github.com/MCMrARM/revolution-irc/commit/ef2fd428c43a323caafd7ac436f9727601b9791c
For the `account-tag` support, please open a separate issue.
