### ISSUE TITLE
missing handling of ircs: URL scheme

### ISSUE THREAD

**Issue by thestinger** [MCMrARM/revolution-irc#270]
As an example, there's an ircs: link listed in the footer of https://freenode.net/ as the main way to join with an IRC client.

**Comment by MCMrARM** [comment]
There is irc: link support, so it should be trivial to add ircs: support. PR welcome.

**Comment by MCMrARM** [comment]
Fixed by https://github.com/MCMrARM/revolution-irc/commit/c4ab0b028291601fb20ffb35a6e769cb8cb3b289 and https://github.com/MCMrARM/revolution-irc/commit/f1507317425b2641cac7c07777ea0dffc1d20be3
