### ISSUE TITLE
0.5.3 crashes on LOS17.1

### ISSUE THREAD

**Issue by llluuuzzziii** [MCMrARM/revolution-irc#272]
Hi
Update 0.5.3 crashes with

12-31 00:07:25.426 E/LoadedApk(1317): java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/io.mrarm.irc-V_3xZQ_ia_8HN0MtHdkyYQ==/lib/arm64, /system/lib64, /product/lib64]]

**Comment by alexxcons** [comment]
dup. of #273 ?
