### ISSUE TITLE
Version 0.5.3 crashes when upgrade from version 0.5.2

### ISSUE THREAD

**Issue by Hauffmann** [MCMrARM/revolution-irc#273]
After clean install it works, but crashes again after trying to restore data from the previous version.

**Comment by tanju** [comment]
It crashes too if you try to switch to custom theme and keeps crashing after that on each app restart.

**Comment by ljl-covid** [comment]
The crash log I get (I hope it's the right parts of the right logs) is

`01-01 19:36:29.662  1239  1318 I ActivityManager: Start proc 20891:io.mrarm.irc/u0a148 for activity io.mrarm.irc/.MainActivity
01-01 19:36:29.759  1239  1318 W ActivityManager: Slow operation: 53ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
01-01 19:36:29.855   961  1092 E vendorRil: vendor_ril_send_hook_response: command id is 590829 
01-01 19:36:29.855   961  1092 E vendorRil: print respdataSizeDEF = 0
01-01 19:36:29.865 20891 20891 D AndroidRuntime: Shutting down VM
01-01 19:36:29.866 20891 20891 E AndroidRuntime: FATAL EXCEPTION: main
01-01 19:36:29.866 20891 20891 E AndroidRuntime: Process: io.mrarm.irc, PID: 20891
01-01 19:36:29.866 20891 20891 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "java.lang.Object com.google.gson.TypeAdapter.read(com.google.gson.stream.JsonReader)"
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:932)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.google.gson.Gson.fromJson(Gson.java:870)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at io.mrarm.irc.util.theme.ThemeManager.loadTheme(ThemeManager.java:111)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at io.mrarm.irc.util.theme.ThemeManager.reloadThemes(ThemeManager.java:98)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at io.mrarm.irc.util.theme.ThemeManager.<init>(ThemeManager.java:71)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at io.mrarm.irc.util.theme.ThemeManager.getInstance(ThemeManager.java:43)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at io.mrarm.irc.ThemedActivity.setTheme(ThemedActivity.java:42)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-01 19:36:29.866 20891 20891 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-01 19:36:29.870  1239 20834 W ActivityManager:   Force finishing activity io.mrarm.irc/.MainActivity
01-01 19:36:29.881  1239 20907 W DropBoxManagerService: Dropping: data_app_crash (1717 > 0 bytes)
01-01 19:36:29.886  1239  1360 I ActivityManager: Showing crash dialog for package io.mrarm.irc u0
`

**Comment by MCMrARM** [comment]
Sorry for this, I will look into this and fix this tomorrow.

**Comment by slingamn** [comment]
I experienced this as well, but was able to fix it by uninstalling and reinstalling.

However, even after this I found 0.5.3 to be unstable. I had an incident where it reset my theme from dark to light, and wouldn't let me change back. When I tried to use the "custom theme" option, the application went into a crash-on-startup loop.

**Comment by alexxcons** [comment]
As well crash on startup here after upgrading from 0.5.2 to 0.5.3.
I wanted to go back to 5.0.2 by installing the previous version via fdroid .. some error message/does not work.

So I deinstalled 5.0.3, while keeping its data, installed 0.5.2 --> Works, but my settings are not loaded any more :rage:  Hope that the fix will make my settings work again ! 

If 5.0.3 contains non-backward compartible changes, please dont release it as a bugfix release!  It should be called 0.6.0 instead !

If you need any further information / debug log, just let me know !

**Comment by MCMrARM** [comment]
This is fixed with https://github.com/MCMrARM/revolution-irc/commit/eecf101b574fbbf29fde16a409252fdd2bcea85b

The app appears to work. Probably should write UI tests when I have some time so this doesn't happen again.
