### ISSUE TITLE
Access history

### ISSUE THREAD

**Issue by yashpalgoyal1304** [MCMrARM/revolution-irc#286]
Hello, is there some way i can access the chat history offline? If not, i think this feature is quite important for me.

I know that chat history is saved on the device, but to see that, u have to go online and join the channel too, which is a bit inconvenient thing to do just to be able to look old/existing chat logs {and i dont even remember what channels they were}.

Side: can a channel be watched without joining?? i.e. the online chats.

**Comment by MCMrARM** [comment]
You can not watch channels w/o joining on IRC. The other options are not currently supported.
