### ISSUE TITLE
Export chats

### ISSUE THREAD

**Issue by yashpalgoyal1304** [MCMrARM/revolution-irc#287]
Hi, 

### What?
having an option to export chats would be really handy ...

### Any Special Reason?
... as Telegram app recently made the feature to import chats available [tg_blog🡭](https://telegram.org/blog/move-history) . 

### Use Case:
... As i use IRC for support only, i'd like to be able to import the IRC_revs chats in telegram so that i can easily use telegram's feature like search, easy list of all chats, offline accessible cache ( see #286 ) and mutliple device syncing so that i can easily and quickly see them (the support advices, and steps to follow etc) on any device i want.

Thanks.

**Comment by yashpalgoyal1304** [comment]
hi, i was just thinking about it, and i recalled that in order for the logs export to be importable in telegram, it'd have to be separate per chat (per channel, etc). So, just thought to bring this to your notice too.

Maybe option can be given in export: Export each chat in a separate file
And also in each chat in 3 dots menu.

Or if this seems too much work, then it's obv your wish if u want to even implement it or not. Whatever ur decision will be, i have faith that u will choose whats optimum.

Ask me if you need any other user-side input :)

**Comment by kurahaupo** [comment]
Maybe put all the logs into a zipfile or tarball?

**Comment by kurahaupo** [comment]
@MCMrARM 

Related to this, please add a periodic `fsync()` (or equivalent) to ensure that logs are not lost if the app is abnormally terminated - such as by power loss, or by rebooting after an OS upgrade, or by crashing.

It's particularly distressing to find that some important PM has been lost because the device has shut down or rebooted while unattended.

**Comment by MCMrARM** [comment]
> @MCMrARM
> 
> Related to this, please add a periodic `fsync()` (or equivalent) to ensure that logs are not lost if the app is abnormally terminated - such as by power loss, or by rebooting after an OS upgrade, or by crashing.
> 
> It's particularly distressing to find that some important PM has been lost because the device has shut down or rebooted while unattended.

That sounds like a sqlite `COMMIT` is missing; that's weird, I should look into it.

**Comment by yashpalgoyal1304** [comment]
hi, any updates on this?? i am moving to a new phone now and will have to dump old phone. so... didnt want to loose the chat logs.

**Comment by AdamRGrey** [comment]
RIP

would've been great

**Comment by kurahaupo** [comment]
For a one-off export, such as if you're decommissioning a phone, this can accomplished by performing a device backup to Google, and then using Google Takeout to download the device backups to your PC, and extract the chat logs from there.
