### ISSUE TITLE
Crash when connecting to a ZNC 1.7 bouncer

### ISSUE THREAD

**Issue by TheMythPT** [MCMrARM/revolution-irc#3]
App don't connect to passworded server (as zncs) and crashes.
If you try to reopen the app, it crashes again (maybe while it's trying to connect?).
Except that, seems very interesting.
Any update soon?

**Comment by michcioperz** [comment]
It does connect to my ZNC without issues so that might or might not be a more complex issue

**Comment by TheMythPT** [comment]
I'm using znc 1.7.x, from github, and it crashes when connecting. tried in other zncs from other providers and the same issue remains.

**Comment by MCMrARM** [comment]
I use ZNC 1.6.x, so it might be an issue with 1.7.x. I'll try to check the newer release.

**Comment by TheMythPT** [comment]
I have no firewall on the remote machine, etc. nothing that could block the connection.
hope it's easy to fix and looking forward to a new release.
I'm quite impressed with the app quality.
great job!

**Comment by TheMythPT** [comment]
I can confirm that's some problem related to znc 1.7.x
Tried znc 1.6.3 from a znc provider and the app does connect well.
But still, no idea of what could be.

**Comment by MCMrARM** [comment]
Most likely a connection command I don't properly support. I'll fix it once I set up a ZNC 1.7.x server myself.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/chatlib/commit/f03d041a142b70610cd33693d1d06dbc0064b226
