### ISSUE TITLE
Send as raw doesn't clear input

### ISSUE THREAD

**Issue by svbeon** [MCMrARM/revolution-irc#31]
When sending an unrecognized command you get the prompt "No such command was found. Send as raw" if you press send as raw the input doesn't get cleared as it does when messages or other commands are sent, it'd be great if it did

**Comment by Mikaela** [comment]
I have thought this as feature and liking it especially if I have needed to send multiple commands in sequence or I have been typoing.

**Comment by svbeon** [comment]
@Mikaela I can see the value of it, but at the same time it becomes inconsistent when recognized commands does clear the input whilst raw ones doesn't

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/revolution-irc/commit/17d5b40624091e09823dfcfc3608576c997123d5
