### ISSUE TITLE
Open active channel instead of server list after returning to the app

### ISSUE THREAD

**Issue by ecwpa** [MCMrARM/revolution-irc#33]
First of all, great app.  I'm enjoying it a lot after years of looking for a good replacement for AndChat.  The interface is intuitive and it has all the features a modern IRC clients should have.

But it be great if the app could remember what channel I was in before minimizing so it's just there after maximizing it again instead of returning to the server list, especially when you're only connected to one server.

**Comment by MCMrARM** [comment]
I guess this is a bug. The application should automatically show the last channel when reopened because it should be saved in the activity state. I'll investigate it soon.

**Comment by ecwpa** [comment]
I see.  Let me know if you need any assistance from my part.

**Comment by MCMrARM** [comment]
I can't reproduce this issue on Android 7.1 on my OnePlus 5 unfortunately. What Android version and device do you use?

**Comment by haarp** [comment]
For me, this happens on an LG-D802 with Cyanogenmod 13.0 (Android 6.0.1). When I am viewing a channel, press the home button, then open the app again via the app icon in the launcher, I end up in the server manager.

**Comment by MCMrARM** [comment]
Fixed: https://github.com/MCMrARM/revolution-irc/commit/a63317e546c7e0a0074b6c7332bc714a4df7d95b
