### ISSUE TITLE
No Connection Over SASL!

### ISSUE THREAD

**Issue by sallyhaj** [MCMrARM/revolution-irc#344]
Hello there,
I want to connect the App to libera.chat server, when I do without SASL, it connects just fine, but when I try to use encryption SASL, it refused to connect, even though, it shows that, it's connecting, but keeping trying, with the indication that, it's Disconnected.
So, I can't join any channels.
I have captured screenshots for that.
Thank you so much.
![Screenshot_2023-07-13-23-46-06-24_5b852a861188494bed1cc0f3776519d5](https://github.com/MCMrARM/revolution-irc/assets/109706/a986fd26-83c6-4b95-a748-efd4db57b1e9)
![Screenshot_2023-07-14-00-06-46-77_5b852a861188494bed1cc0f3776519d5](https://github.com/MCMrARM/revolution-irc/assets/109706/e16e47fe-5b29-4735-98ad-606acdf3af00)

**Comment by sallyhaj** [comment]
The problem was regarding the uses of Nickname in other application, yes, it's the same account with same username, but the nickname should be different, so I have added "myNickname_", and that fixed the issue.
Thank you for @MCMrARM mrarm and roo^y from #revolutionirc channel.

**Comment by DeveloperMelodica** [comment]
> The problem was regarding the uses of Nickname in other application, yes, it's the same account with same username, but the nickname should be different, so I have added "myNickname_", and that fixed the issue. Thank you for [@MCMrARM](https://github.com/MCMrARM) mrarm and roo^y from #revolutionirc channel.

Thanks a lot, didn't know what was wrong :)
