### ISSUE TITLE
Revolution appears to decode non-UTF-8 charset

### ISSUE THREAD

**Issue by Mikaela** [MCMrARM/revolution-irc#35]
> Where are Revolution IRC charsets configured? I just noticed that it's decoding something else than UTF-8 and I hope that it's at least sending UTF-8. I don't like messages getting decoded from other charsets as I run multiple relay bots and if someone is using wrong charset, I cannot immediately see that from Revolution.
> Mikaela: if the character encodings are an issue for you, please open an GitHub issue

**Comment by MCMrARM** [comment]
Well, for me it does decode UTF-8 correctly. I'll look into this later.

**Comment by MCMrARM** [comment]
I believe this is not an issue in the current version and am closing the issue therefore.
