### ISSUE TITLE
/whois nick nick only shows two line response rather than the full response 

### ISSUE THREAD

**Issue by Mikaela** [MCMrARM/revolution-irc#37]
When I run `/whois nick nick` (on charybdis-4-rc7) I expect to see the same as with any other client (Weechat):

* user@host: Real Name
* channel list
* IRC server and description
* SSL connection if it's used
* SSL certificate fingerprint if used
* the actual host where the user is connecting from
* idle time
* NickServ username

What I see instead is:

* SSL certificate fingerprint if used
* the actual host where the user is connecting from

I am oper and I mainly use Revolution IRC for connecting to ZNC which is opered.

**Comment by Mikaela** [comment]
The issue seems to be that Revolution eats WHOIS when it's done manually and only shows whois when it's done from the nicklist which was option I was unaware of until I accidentally used it.

I guess my request would be allowing me to use WHOIS manually or even if I am not sharing a channel with the target.

**Comment by MCMrARM** [comment]
Sub-issues:
- /whois is kind-of case-sensitive (client-side case-sensitive), it should not be.
- In the case of an unasked-for /whois, the /whois is not displayed anywhere, it likely should end up in the Server tab
- Add some currently unsupported misc info into the whois window

**Comment by MCMrARM** [comment]
Fixed /whois being case sensitive (https://github.com/MCMrARM/chatlib/commit/189221042211b2409201993c68f645bcf24ec073), made all /whois requests show up in the server tab, and created a separate issue for the misc info still not in the dialog.

**Comment by kurahaupo** [comment]
Just wanted to add a "thankyou"; the way it works now is a great improvement - I can see the nicely formatted form, and it's in the history in the SERVER tab, so I can click to see it again without re-sending the request to the server.
