### ISSUE TITLE
Short loss in connection causing connection to be dropped completely

### ISSUE THREAD

**Issue by Vexatos** [MCMrARM/revolution-irc#39]
I recently noticed that whenever my phone loses signal for a short time (even if it's only a a second or less on a spotty wifi connection), the app immediately considers every server disconnected and tries reconnecting from scratch instead of just waiting until the connection is back. It would be a good idea to have a timeout for when the connection should be considered lost.

**Comment by MCMrARM** [comment]
I'm unsure if this is even possible to implement. Any examples of apps that do that?

**Comment by MCMrARM** [comment]
Impossible.
