### ISSUE TITLE
Duplicate queries

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#41]
It is possible to have two queries with a single users due to case mismatch. Easiest way to reproduce:
```
/msg ChanServ HELP
/msg chanserv HELP
```

**Comment by Mikaela** [comment]
I think these also happen with raw commands like `CHANSERV help` which makes ChanServ send the first message.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/chatlib/commit/9152e5c045d6b07f385c0050322f7e2fb55ebb62
