### ISSUE TITLE
NickServ auth

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#42]
Add support for using NickServ auth in addition to SASL. This was required in a Google Play beta review.

**Comment by MCMrARM** [comment]
After thinking about this issue for a while:
I do not want people to use the deprecated NickServ way of authentication instead of SASL. Because of this I will not add an easy-to-use option to select NickServ and instead implement on-connect command list. It'll still be possible to achieve NickServ authentication for those who need it using it but it'll not make people prefer it over SASL.

**Comment by MCMrARM** [comment]
On a second thought:
I'll implement NickServ auth directly but will show up a dialog asking you to make sure the server doesn't support SASL.

**Comment by Mikaela** [comment]
So how does this work? Will it send `IDENTIFY password` to NickServ? What if NickServ wants `identify username password` or even `identify password username` or something?

SASL is the only standardized way of identifying to different services packages, and I would close this issue in favour of #47.

**Comment by MCMrARM** [comment]
The problem with this is basically that then the password will be displayed in clear text.

**Comment by MCMrARM** [comment]
Decided to implement #47 instead of this.
