### ISSUE TITLE
How can I translate it to a foreign language?

### ISSUE THREAD

**Issue by OriginCode** [MCMrARM/revolution-irc#44]
Well, how can I do...
My classmate wants to use it, but he is not so good at English.

**Comment by MCMrARM** [comment]
Here's the strings.xml file: https://github.com/MCMrARM/revolution-irc/blob/master/app/src/main/res/values/strings.xml
You could translate it now, but be prepared to update it every major release.

**Comment by OriginCode** [comment]
THX!
I will translate it soon!
