### ISSUE TITLE
Post-connection commands

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#47]
Plenty of IRC clients have an option to execute IRC commands after joining a channel and so I would like to add this feature to my client. However, I'm not quite sure about the use-cases -- NickServ support will be implemented first and I don't really see why would anyone need this.

If you want this feature, please comment on this issue what would you use it for.

**Comment by Mikaela** [comment]
Some use cases:

* setting umodes on connect (+R to block PMs from unidentified users, +g for blocking PMs from everyone unless they have been ACCEPTed, +w for seeing wallops)
* ACCEPT goodperson
* OPERing up
* PRIVMSG ancientbot :identify username password
    * quakenet login

I think the first usecase would also need something like `$nick` that would automatically get replaced with the current nick or the commands would fail.

**Comment by MCMrARM** [comment]
Another question: When to run the command? Before connecting or after we're connected (post-MOTD?)?

**Comment by Mikaela** [comment]
I think that they should be ran as soon as possible.

**Comment by Madbrad200** [comment]
Another one is using /silence which is a server side ignore that removes itself after you disconnect.

**Comment by MCMrARM** [comment]
This is now implemented.
