### ISSUE TITLE
New join/part messages are not hidden

### ISSUE THREAD

**Issue by n-st** [MCMrARM/revolution-irc#49]
Activating the "Hide Join/Part messages" options removes all join and part messages that exist at the time the option is activated, but any new joins/parts after that are displayed normally.  
The process can be repeated (i.e. disabling and reenabling the option) with the same result.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/revolution-irc/commit/3cda62e1a1cfb946d35ecd85587033f98a148034
