### ISSUE TITLE
New message marker

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/revolution-irc#50]
When new messages are shown, a line separating the old messages from new should be shown.

**Comment by TheMythPT** [comment]
Also, thinking about znc users, would it be possible to add a day marker?
Perhaps something like:
`-----23/12/2017-----`

**Comment by MCMrARM** [comment]
Sneak preview:
![Image](https://mrarm.io/u/Clipboard%202019-01-20%2015-13-09.png)

Notifications now also jump to the message that caused the ping.

**Comment by MCMrARM** [comment]
I'm also considering adding a separator line but that's a bit more work so I'm not sure whether it will happen for 0.5.

**Comment by MCMrARM** [comment]
Preview:
![Image](https://mrarm.io/u/Clipboard%202019-01-20%2022-13-19.png)

**Comment by MCMrARM** [comment]
![Image](https://mrarm.io/u/Clipboard%202019-01-20%2015-13-09.png)

**Comment by MCMrARM** [comment]
This has been mostly implemented, so I'm closing the issue.
