### ISSUE TITLE
Add ident@host to join/part/quit messages

### ISSUE THREAD

**Issue by TheMythPT** [MCMrARM/revolution-irc#52]
Right now, when someone joins/parts/quits, the messages are just like: nick joined/parted/quited.
For channel operators, having something like `nick (ident@host) has joined` would be great, for ban purposes or even to control trolls.

**Comment by rud01f** [comment]
I second that, it would be helpful to many users.

**Comment by MCMrARM** [comment]
Implemented by https://github.com/MCMrARM/revolution-irc/commit/2fcf34e4b313e76071ac07d52161c5014af2b722
