### ISSUE TITLE
Add server tab to the "channels list" and name it Status Window/Server Window/whatever

### ISSUE THREAD

**Issue by TheMythPT** [MCMrARM/revolution-irc#53]
When using sensitive commands on IRC, i like to write them all in the server window. But currently in order to get into the server window, we need to open the menu, choose the 1st channel on the list and then swipe to the right. Making it visible on above all channels, would make things easier.

**Comment by MCMrARM** [comment]
@kurahaupo I guess not a bad idea, I'll do that.

**Comment by kurahaupo** [comment]
Since the triangles are quite small, please extend the fold/unfold button around them, perhaps even into the start of the server name, maybe even to 25% of the width of the tab.

**Comment by MCMrARM** [comment]
I'll add a Server tab to the drawer by default and an option to always show it instead, as by observing my own usage I noticed that I often collapse the server by tapping anywhere inside the element instead of using the expand arrow.

**Comment by MCMrARM** [comment]
Implemented.

**Comment by kurahaupo** [comment]
Just wanted to say thanks, I like the way it's working now.
