### ISSUE TITLE
[Request] Darker dark theme

### ISSUE THREAD

**Issue by AeliusSaionji** [MCMrARM/revolution-irc#55]
The provided dark theme doesn't make use of the color black!

I'd like to make use of my AMOLED display :)

**Comment by MCMrARM** [comment]
More advanced theming is planned for 0.4.0 :)

**Comment by prg318** [comment]
Just wanted to bump this and mention that it's not possible for a pure black background even with the advanced themeing features of of 0.4.x

Would really love to see a "Black" option for the background for AMOLED display

**Comment by prg318** [comment]
https://github.com/prg318/revolution-irc/tree/0.4.1-black

I made a very hacky patch to support this.  I plan to at some point (when/if I get time) to implement a proper toggle option in "Interface" options, clean up, and submit a PR upstream.

**Comment by MCMrARM** [comment]
There were no advanced theming features in the 0.4 release. Postponed until a later release.

I still plan to add this, but I want to do it properly, and therefore I didn't make it in time.

**Comment by MCMrARM** [comment]
Even though this is not a dark theme, an improved theming system will be available in the next release, with this being an example:
![Example](https://mrarm.io/u/Screenshot_20190113-200430.jpg)

Currently due to the Material color picker a completely-dark theme can't be done but this will be improved before the release.

**Comment by MCMrARM** [comment]
Here's an example of a fully dark theme:
![Screenshot 1](https://mrarm.io/u/Screenshot_20190113-224616.jpg)
![Screenshot 2](https://mrarm.io/u/Screenshot_20190113-224706.jpg)
