### ISSUE TITLE
Add notification ignore

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#60]
It would be nice if you could ignore notifications from certain nicks or patterns. Basically a "negative" custom rule.

This is to avoid getting pointlessly pinged by services such as NickServ

**Comment by MCMrARM** [comment]
This is already fully possible. Simply create a rule and uncheck show notification.

**Comment by haarp** [comment]
I just gave it a try, it does indeed work. Thanks for letting me know! Maybe it could be made a bit more discoverable, hmm.
