### ISSUE TITLE
Configurable notification behavior

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#64]
It would be great if the notification behavior (the default one) could be configurable. Things such as vibration pattern, sound, notification light color, which are currently only available for custom notifications.

In addition, it should also be configurable separately for when the app is in the foreground. In such a case for example I do not need vibrations or sounds, a visual indicator in the app is enough.

**Comment by MCMrARM** [comment]
Those are configurable, just tap on the default rule names.

Please open another issue for the foreground and background rule separation.

**Comment by haarp** [comment]
Ooh, I did not notice this! I didn't think the default notifications were configurable, as the buttons look like they only have the checkbox available to them. Thanks for letting me know. Maybe this could be made a bit more obvious?

I opened #67 for the foreground thing.
