### ISSUE TITLE
Chat log boxes become empty

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#68]
Under certain circumstances (I haven't managed to reproduce this reliably yet), a bug is triggered.

As a result, the chat log boxes under all tabs and on all networks show up empty. It doesn't matter if someone has written something in them.

The only exception are Server tabs, these still show their proper content.

The only solution so far is to restart the app.

**Comment by MCMrARM** [comment]
This is most likely fixed by https://github.com/MCMrARM/chatlib-android-storage/commit/3893d0e6721a2766f95c1440dbedaa22c948c38c

**Comment by Mikaela** [comment]
I have last experienced this today, but I fix it by disconnecting and reconnecting which does sometimes causes some messages to be lost.

**Comment by michcioperz** [comment]
@Mikaela Are you on 0.3.2? I experience it fairly often there; but I think the fix hasn't reached the available releases just yet. Soon™ (MrARM mentioned a new build might come in a few days)

**Comment by Mikaela** [comment]
Yes, according to app details, I thought it would be fixed in three months from issue getting closed. I hope to see the fixed version soon, I think I am on beta channel.
