### ISSUE TITLE
No open channels -> Can't switch to server in menu

### ISSUE THREAD

**Issue by haarp** [MCMrARM/revolution-irc#70]
When a server is open that has 0 tabs, it becomes impossible to switch to it from the left-side menu. Tapping the server name only expands/collapses the (empty) channel list.

One has to go to "Manage servers" to be able to reach it again.

Ideally, when there's 0 tabs, tapping the server name should go to the server instead of expanding/collapsing an empty tree.

**Comment by kurahaupo** [comment]
Would be resolved by implementing #53

**Comment by kurahaupo** [comment]
Now that we have a separate “server” tab, is this issue fixed?

**Comment by MCMrARM** [comment]
Yes, it is.
