### ISSUE TITLE
Crash on connecting to gitter

### ISSUE THREAD

**Issue by gheoan** [MCMrARM/revolution-irc#74]
Connecting to the `irc.gitter.im` server using version 0.3.2 results in crash. Check https://irc.gitter.im/  for instructions on how to connect. Let me know if more information is needed.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/chatlib/commit/a87737f8987ebd1eb6768c1a6df431b3ee1f5bdb
