### ISSUE TITLE
[REQUEST] Connecting to TLS-encrypted networks

### ISSUE THREAD

**Issue by SudosFTW** [MCMrARM/revolution-irc#79]
one of the servers I frequent with the box I usually keep irssi connected on requires TLS as the encryption standard for various reasons since the owner of the server is pretty tinfoil-hatted about such things. 

Specifically, the server uses **TLSv1.2-ECDHE-RSA-AES256-GCM-SHA384-256bits** encryption, so says the server status page. 

I don't really see any other IRC clients for Android supporting this-- it might be a good selling point of your client over others to allow for it, since SSL has had problems in the past and everyone will start moving towards this in the future of things as time goes on.

**Comment by MCMrARM** [comment]
As for the encryption I simply use whatever the OS provides -- if it supports TLS, nice, otherwise nope. Recent Android versions should support most of the encryption standards.

I do not know why does this take longer -- how long is 'a lot of time'?

**Comment by jgkamat** [comment]
Just wanted to say that I'm connecting to my encrypted bouncer just fine, with no extra issues, just had to check the 'use SSL' box, and it seemed to work.

**Comment by ZeroKnight** [comment]
> As for the encryption I simply use whatever the OS provides -- if it supports TLS, nice, otherwise nope.

To elude to this in the UI, it might be worthwhile to change the check box to: "Use SSL/TLS", or a more generic "Use Encryption".

**Comment by MCMrARM** [comment]
Renamed the checkbox to Use SSL/TLS: https://github.com/MCMrARM/revolution-irc/commit/2eec0bd71a1d3065598935af9f7618804535a500
