### ISSUE TITLE
[REQUEST] dcc support

### ISSUE THREAD

**Issue by decripter37** [MCMrARM/revolution-irc#83]
As title says, I'd like a dcc support.
Nice app btw, thanks!

**Comment by KOLANICH** [comment]
TIME and VERSION shouod be disableable (the fact that these messages are disabled shouldn't affect CLIENTINFO response) and overrideable. A user should be able to enable rate-limited notifications when someone sends him such DCCs.

**Comment by benrob0329** [comment]
Firewall/NAT traversal would need to be explored for this, otherwise DCC is darned near useless.
