### ISSUE TITLE
How do I list users on a channel?

### ISSUE THREAD

**Issue by Kreijstal** [MCMrARM/revolution-irc#87]
I am not able to know who  is on, on a server

**Comment by MCMrARM** [comment]
Swipe from right :)

**Comment by Kreijstal** [comment]
how nonuintuitive! A guide would be nice though.

**Comment by Bilb** [comment]
Got the same question, a guide would be really nice in fact ! I will check to do a pull request with a tiny change soon.

**Comment by Bananamax** [comment]
And how to make the userlist visible on the right at all times? That has to be a possibility. I want to write AND see the people in the channel. On a tablet ofc there is enough space for that.

**Comment by Bilb** [comment]
By channel you mean opengroup? 
If yes, there is a no way to get the users of an opengroup except by reading the messages sent.
